socializer/application/users/models.py
import datetime

from sqlalchemy.ext.hybrid import hybrid_property

from application import db, flask_bcrypt_instance
from application import user_followed
from application.posts.models import Post

__all__ = ["followers", "User"]

followers = db.Table(
    "followers",
    db.Column(
        "follower_id", db.Integer, db.ForeignKey("user.id"), primary_key=True
    ),
    db.Column(
        "user_id", db.Integer, db.ForeignKey("user.id"), primary_key=True
    )
)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    username = db.Column(db.String(40), unique=True)
    _password = db.Column("password", db.String(60))
    created_on = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    followed = db.relationship(
        "User",
        secondary=followers,
        primaryjoin=(id==followers.c.follower_id),
        secondaryjoin=(id==followers.c.user_id),
        backref=db.backref("followers", lazy="dynamic"),
        lazy="dynamic"
    )

    def __repr__(self):
        return '<User {!r}>'.format(self.username)
    
    def is_authenticated(self):
        return True
    
    def is_active(self):
        return True
    
    def is_anonymous(self):
        return False
    
    def get_id(self):
        return str(self.id)

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        """Bcrypt the password on assignment"""
        self._password = flask_bcrypt_instance.generate_password_hash(password)

    def unfollow(self, user):
        """Unfollow the given user
        
        :return false if user was not followed
            otherwise:
                remove user from the followed list and return
                current object to be committed to the session
        """
        if not self.is_following(user):
            return False
        self.followed.remove(user)
        return self
    
    def follow(self, user):
        """Follow given user
        return false if user was already followed
        """
        if self.is_following(user):
            return False
        self.followed.append(user)

        # Emit a signal that the user was followed
        user_followed.send(self)

        return self
    
    def is_following(self, user):
        """Returns true if current_user following user, false otherwise"""
        followed = self.followed.filter(followers.c.user_id == user.id)
        return followed.count() > 0
    
    def newsfeed(self):
        """Return all posts from users that this user follows."""
        join_condition = followers.c.user_id == Post.user_id
        filter_condition = followers.c.follower_id == self.id
        ordering = Post.created_at.desc()

        return Post.query.join(
            followers, join_condition
        ).filter(filter_condition).order_by(ordering)

socializer/application/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, g, current_app
from flask_login import login_user, logout_user, login_required, current_user

from sqlalchemy import exc

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length

from application.users.models import User
from application import db, flask_bcrypt_instance

users = Blueprint('users', __name__, template_folder="templates")


class LoginForm(FlaskForm):
    """Basic login form and validation"""

    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField(
        'Password', validators=[DataRequired(), Length(min=6)]
    )


class CreateUserForm(FlaskForm):
    """Basic user creation form and validation"""

    email = StringField('Email', validators=[DataRequired(), Length(min=6)])
    username = StringField(
        'Username', validators=[DataRequired(), Length(min=3)]
    )
    password = PasswordField(
        'Password', validators=[DataRequired(), Length(min=6)]
    )


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    form = CreateUserForm()
    if form.validate_on_submit():
        email = form.email.data
        username = form.username.data
        password = form.password.data

        user = User(email=email, username=username, password=password)
        try:
            db.session.add(user)
            db.session.commit()
            flash('User successfully created')
            login_user(user, remember=True)
            return redirect(url_for('users.index'))
        except exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.error("User unique constraint failed: %s", e)
            flash('User already exists')
            return render_template('users/login.html', form=form)
        except exc.SQLAlchemyError as e:
            current_app.exception("Database error: {e}".format(e=e))
            return render_template('users/signup.html', form=form)


    return render_template('users/signup.html', form=form)

@users.route('/', methods=['GET'])
def index():
    return render_template('users/index.html')

@users.route('/login', methods=['GET', 'POST'])
def login():
    if hasattr(g, 'user') and g.user.is_authenticated:
        return redirect(url_for('users.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(username=form.username.data).one()
        except exc.NoResultFound:
            flash(
                "User {username} does not exist".format(
                    username=form.username.data
                )
            )
            # after fialing render with form data is better
            return render_template('users/login.html', form=form)
        
        if not user or not flask_bcrypt_instance.check_password_hash(
            user.password, form.password.data
        ):
            flash('Invalid username or password')
            return redirect(url_for('users.login'))

        login_user(user, remember=True)
        # after successful redirect avoids form submission,
        # and correctly updates the URL
        return redirect(url_for('users.index'))
        # return render_template('users/index.html', form=form)
    
    return render_template('users/login.html', form=form)

@users.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route("/feed", methods=["GET"])
@login_required
def feed():
    """List all posts for authenticated user; most recent first."""
    posts = current_user.newsfeed()
    return render_template("users/feed.html", posts=posts)

socializer/application/users/templates/users/feed.html
{% extends "layout.html"}

{% block content %}
    <div class="new-post">
        <p>< a href="{{url_for('post.add')}}">New Post</a></p>
    </div>

    {% for post in posts %}
        <div class="post">
            <span class="author">{{post.user.username}}</span>, published on <span class="date">{{post.created_at}}</span>
            <pre><code>{{post.content}}</code></pre>
        </div>
    {% endfor %}
{% endblock %}

socializer/application/users/templates/users/index.html
{% extends "layout.html" %}

{% block content %}

<div>Hello {{ user }} </div>
    
{% endblock %}

socializer/application/users/templates/users/login.html
{% extends "layout.html" %}

{% block content %}

<form action="{{ url_for('users.login') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.id }}
    <div>{{ form.username.label }}: {{ form.username }}</div>
    {% if form.username.errors %}
    <ul class="errors">
        {% for error in form.username.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div>{{ form.password.label }}: {{ form.password }}</div>
    {% if form.password.errors %}
    <ul class="errors">
        {% for error in form.password.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div><input type="submit" value="Login"></div>
</form>
    
{% endblock %}

socializer/application/users/templates/users/signup.html
{% extends "layout.html" %}

{% block content %} 
<form action="{{ url_for('users.signup') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.id }}
    <div>{{ form.username.label }}: {{ form.username }}</div>
    {% if form.username.errors %}
        <ul class="errors">
        {% for error in form.username.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}

    <div>{{ form.email.label }}: {{ form.email }}</div>
    {% if form.email.errors %}
        <ul class="errors">
        {% for error in form.email.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}

    <div>{{ form.password.label }}: {{ form.password }}</div>
    {% if form.password.errors %}
        <ul class="errors">
        {% for error in form.password.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %} 

    <div><input type="submit" value="Sign Up"></div>
</form>
{% endblock %}