snap/application/snaps/models.py
import datetime
import hashlib
import uuid

from sqlalchemy import orm, event

from application import db


class Snap(db.Model):

    # The primary key for each snap record
    id = db.Column(db.Integer, primary_key=True)

    # The name of the file; dows not need to be unique
    name = db.Column(db.String(128))

    # The extension of the file used for syntax highlighting
    extension = db.Column(db.String(12))

    # The content of the Snap
    content = db.Column(db.Text())

    # The unique, un-guessable IF of the file
    uuid = db.Column(
        db.String(36), unique=True, default=lambda: str(uuid.uuid4())
    )
    hash_key = db.Column(db.String(40), unique=True)

    # The date/time when snap was created
    created_on = db.Column(
        db.DateTime, default=datetime.datetime.utcnow, index=True
    )

    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    user = db.relationship("User", backref=db.backref("naps", lazy="dynamic"))

    def __repr__(self):
        return "<Snap {!r}>".format(self.id)
    
    @orm.reconstructor
    def init_on_load(self):
        """Called when loading instance from the database, the same as init"""
        if not self.hash_key:
            self.hash_key = self.content_hash()

    def content_hash(self):
        """sets context-sensitive default function"""
        if self.content and self.created_on:
            return hashlib.sha1(
                (self.content + str(self.created_on)).encode("utf-8")
            ).hexdigest()
        else:
            return None

    def __init__(self, name, extension, content, user_id):
        self.name = name
        self.extension = extension
        self.content = content
        self.user_id = user_id
        self.created_on = datetime.datetime.utcnow()
        self.hash_key = self.content_hash()

@event.listens_for(Snap, "before_insert")
def receive_before_insert(mapper, connection, target):
    if not target.hash_key:
        target.hash_key = target.content_hash()

snap/application/snaps/views.py
from flask import (
    Blueprint, render_template, url_for, redirect, current_app, flash
)
from flask_login import login_required, current_user

from flask_wtf import FlaskForm
from sqlalchemy import exc
from wtforms import StringField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea

from .models import Snap
from application import db

snaps = Blueprint("snaps", __name__, template_folder="templates")

class SnapForm(FlaskForm):
    """Form for creating new snaps."""
    name = StringField("name", validators=[DataRequired()])
    extension = StringField("extension", validators=[DataRequired()])
    content = StringField(
        "content", widget=TextArea(), validators=[DataRequired()]
    )


@snaps.route("/", methods=["GET"])
def listing():
    """List all snaps, most recent first."""
    snaps = Snap.query.order_by(Snap.created_on.desc()).limit(20).all()
    return render_template("snaps/index.html", snaps=snaps)


@snaps.route("/add", methods=["GET", "POST"])
@login_required
def add():
    """Add a new snap"""
    form = SnapForm()

    if form.validate_on_submit():
        user_id = current_user.id
        snap = Snap(
            user_id=user_id,
            name=form.name.data,
            content=form.content.data,
            extension=form.extension.data
        )
        db.session.add(snap)
        try:
            db.session.commit()
        except exc.SQLAlchemyError:
            current_app.exception("could not save new snap!")
            flash("Something went wrong while posting your snap!")
    else:
        return render_template("snaps/add.html", form=form)
    
    return redirect(url_for("snaps.listing"))

snap/application/snaps/templates/snaps/add.html
{% extends "layout.html" %}

{% block content %}
<form action="{{ url_for('snaps.add')}}" method="post">

    {{ form.hidden_tag() }}
    {{ form.id }}

    <div class="row">
        <div>{{ form.name.label() }}: {{ form.name }}</div>
        {% if form.name.errors %}
        <ul class="errors">{%for error in form.name.errors %}<li>{{ error }}</li>{% endfor %}</ul>
        {% endif %}

        <div>{{ form.extension.label() }}: {{ form.extension }}</div>
        {% if form.extension.errors %}
        <ul class="errors">{% for error in form.extension.errors %}<li>{{ error }}</li>{% endfor %}</ul>
        {% endif %}
    </div>

    <div class="row">
        <div>{{ form.content.label() }}: {{ form.content }}</div>
        {% if form.content.errors %}
        <ul class="errors">{% for error in form.content.errors %}<li>{{ error }}</li>{% endfor %}</ul>
        {% endif %}
    </div>

    <div><input type="submit" value="Snap"></div>

</form>
{% endblock %}

snap/application/snaps/templates/snaps/index.html
{% extends "layout.html" %}

{% block content %}
<div class="new-snap">
    <p><a href="{{ url_for('snaps.add') }}">New Snap</a></p>
</div>

{% for snap in snaps %}
<div class="snap">
    <span class="author">{{ snap.user.username }}</span>, published on <span class="date">{{ snap.created_on }}</span>
    <pre><code>{{ snap.content }}</code></pre>
</div>

{% endfor %}
{% endblock %}