socializer/application/posts/models.py
from application import db
import datetime

__all__ = ['Post']

class Post(db.Model):
    __tablename__ = 'post'
    __table_args__ = {'extend_existing': True}
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text())
    created_at = db.Column(
        db.DateTime(), default=datetime.datetime.utcnow, index=True
    )
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    user = db.relationship('User', backref=db.backref('posts', lazy='dynamic'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

socializer/application/posts/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, g, current_app

from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea
from sqlalchemy import exc

from application.posts.models import Post
from application import db

posts = Blueprint("posts", __name__, template_folder="templates")

class CreatePostForm(FlaskForm):
    """Basic post creation form and validation"""
    content = StringField('Content', widget=TextArea(), validators=[DataRequired()])

@posts.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = CreatePostForm()
    if form.validate_on_submit():
        user_id = current_user.id

        post = Post(content=form.content.data, user_id=user_id)
        try:
            db.session.add(post)
            db.session.commit()
            flash('Post successfully created')
        except exc.SQLAlchemyError as e:
            db.session.rollback()
            current_app.logger.error("Post creation failed: %s", e)
            flash('Post creation failed')

    else:
        return render_template('posts/add.html', form=form)

    return redirect(url_for('users.index'))  
        

socializer/application/posts/templates/posts/add.html
{%extends "layout.html"%}
{%block content%}
<form action="{{url_for('posts.add')}}" method="post">
    
    {{form.hidden_tag()}}
    {{ form.id }}

    <div class="row">
        <div>{{ form.content.label }}: {{ form.content }}</div>
        {% if form.content.errors %}
            <ul class="errors">
                {% for error in form.content.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div><input type="submit" value="Post"</div>
    </form>
{%endblock%}